defaults:
  - default.yaml
  - _self_

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "fid_score"
  mode: min
  save_top_k: 3 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_fid_{fid_score}"
  auto_insert_metric_name: False
