defaults:
  - stylegan_ada.yaml

_target_: src.models.stylegan_module_finetune.StyleGANFinetuneModule

k_blending_layers: 3  # Resolution at 2 ^ (k_blending_layers + 1)
use_ema_for_k_layers: False

hparams:
  # Train specific parameters

  train:

    noise_mode: 'const'  # ['random', 'const'] noise for StyleGAN2 generator, if const will be zeros
    train_mapper: True  # Train StyleGAN mapper or only synthesizer

    face_crop: &face_crop [46, 81, 201, 236]  # Face crop for FFHQ
    style_mixing_prob: 0.1


    ema:
      ema_kimg: 20.0
      ema_rampup: null
    logging:
      img_log_freq: 100

    losses:
      weights:
        id_weight: 0.01

      facial_recognition: # Norm from arcface
        face_crop: *face_crop
        ir_se50_weights: ${hydra:runtime.cwd}/checkpoints/model_ir_se50.pth
        empty_scale: 1.0
        norm:
          mean: &mean [ 0.5, 0.5, 0.5 ]
          std: &std [ 0.5, 0.5, 0.5 ]
    optimizing:
      optimizers:
        optimizer_G:
          lr: &lr_G 0.002
        optimizer_D:
          lr: &lr_D 0.002