defaults:
  - stylegan_ada.yaml

_target_: src.models.stylegan_module_finetune.StyleGANFinetuneModule

k_blending_layers: 3  # Resolution at 2 ^ (k_blending_layers + 1)

hparams:
  # Train specific parameters

  train:
    netD: # Discriminator model
      epilogue_kwargs:
        mbstd_group_size: 4
    noise_mode: 'const'  # ['random', 'const'] noise for StyleGAN2 generator, if const will be zeros
    train_mapper: False  # Train StyleGAN mapper or only synthesizer

    face_crop: &face_crop [46, 81, 201, 236]  # Face crop for FFHQ

    ema:
      ema_kimg: 20.0
      ema_rampup: null

    losses:
      weights:
        id_weight: 1.0

      facial_recognition: # Norm from arcface
        face_crop: *face_crop
        ir_se50_weights: ${hydra:runtime.cwd}/checkpoints/model_ir_se50.pth
        empty_scale: 1.0
        norm:
          mean: &mean [ 0.5, 0.5, 0.5 ]
          std: &std [ 0.5, 0.5, 0.5 ]
    optimizing:
      schedulers:
        interval: 'step'
        scheduler_G:
          max_lr: 0.002
        scheduler_D:
          max_lr: 0.002